XBEE_PARAM(ID, "PAN ID")
XBEE_PARAM(SC, "Scan Channels")
XBEE_PARAM(SD, "Scan Duration")
XBEE_PARAM(ZS, "Zigbee Stack Profile")
XBEE_PARAM(NJ, "Node Join Time")
XBEE_PARAM(NW, "Network Watchdog Timeout")
XBEE_PARAM(JV, "Channel Verification")
XBEE_PARAM(JN, "Join Notification")
XBEE_PARAM(OP, "Operating PAN ID")
XBEE_PARAM(OI, "Ooperating 16bit PAN ID")
XBEE_PARAM(CH, "Operating Channel")
XBEE_PARAM(NC, "Number of Remaining Children")
XBEE_PARAM(CE, "Coordinator Enable")
XBEE_PARAM(DO, "Device Options")
XBEE_PARAM(DC, "Device Controls")
XBEE_PARAM(SH, "Serial Number High")
XBEE_PARAM(SL, "Serial Number Low")
XBEE_PARAM(MY, "16-bit Network Address")
XBEE_PARAM(MP, "16-bit Parent Address")
XBEE_PARAM(DH, "Destination Address High")
XBEE_PARAM(DL, "Destination Address Low")
XBEE_PARAM(NI, "Node Identifier")
XBEE_PARAM(NH, "Maximum Hops")
XBEE_PARAM(BH, "Broadcast Radius")
XBEE_PARAM(AR, "Many-to-One Route Broadcast Time")
XBEE_PARAM(DD, "Device Type Identifier")
XBEE_PARAM(NT, "Node Discovery Backoff")
XBEE_PARAM(NO, "Node Discovery Options")
XBEE_PARAM(NP, "Maximum Number of Transmission Bytes")
XBEE_PARAM(CR, "PAN Conflict Threshold")
XBEE_PARAM(SE, "Zigbee Source Endpoint")
XBEE_PARAM(DE, "Zigbee Destination Endpoint")
XBEE_PARAM(CI, "Zigbee Cluster ID")
XBEE_PARAM(TO, "Transmit Options")
XBEE_PARAM(PL, "TX Power Level")
XBEE_PARAM(PM, "Power Mode")
XBEE_PARAM(PP, "Power at PL4")
XBEE_PARAM(EE, "Encryption Enable")
XBEE_PARAM(EO, "Encryption Options")
XBEE_PARAM(KY, "Encryption Key")
XBEE_PARAM(NK, "Network Encryption Key")
XBEE_PARAM(BD, "Baud Rate")
XBEE_PARAM(NB, "Parity")
XBEE_PARAM(SB, "Stop Bits")
XBEE_PARAM(RO, "Packetization Timeout")
XBEE_PARAM(D6, "DIO6/nRTS Configuration")
XBEE_PARAM(D7, "DIO7/nCTS Configuration")
XBEE_PARAM(AP, "API Enable")
XBEE_PARAM(AO, "API Output Mode")
XBEE_PARAM(CT, "AT Command Mode Timeout")
XBEE_PARAM(GT, "Guard Times")
XBEE_PARAM(CC, "Command Sequence Charecter")
XBEE_PARAM(SP, "Cyclic Sleep Period")
XBEE_PARAM(SN, "Number of Cyclic Sleep Periods")
XBEE_PARAM(SM, "Sleep Mode")
XBEE_PARAM(ST, "Time before Sleep")
XBEE_PARAM(SO, "Sleep Options")
XBEE_PARAM(WH, "Wake Host")
XBEE_PARAM(PO, "Poll Rate")
XBEE_PARAM(D0, "DIO0 Configuration")
XBEE_PARAM(D1, "DIO1 Configuration")
XBEE_PARAM(D2, "DIO2 Configuration")
XBEE_PARAM(D3, "DIO3 Configuration")
XBEE_PARAM(D4, "DIO4 Configuration")
XBEE_PARAM(D5, "DIO5 Configuration")
XBEE_PARAM(D8, "DIO8 Configuration")
XBEE_PARAM(D9, "DIO9 Configuration")
XBEE_PARAM(P0, "DIO10 Configuration")
XBEE_PARAM(P1, "DIO11 Configuration")
XBEE_PARAM(P2, "DIO12 Configuration")
XBEE_PARAM(P3, "DIO13 Configuration")
XBEE_PARAM(P4, "DIO14 Configuration")
XBEE_PARAM(PR, "Pull-up Resistor Enable")
XBEE_PARAM(PD, "Pull-up/down Direction")
XBEE_PARAM(LT, "Associate LED Blink Time")
XBEE_PARAM(RP, "RSSI PWM Timer")
XBEE_PARAM(IR, "IO Sampling Rate")
XBEE_PARAM(IC, "Digital IO Change Detection")
XBEE_PARAM(VR, "Firmware Version")
XBEE_PARAM(HV, "Hardware Version")
XBEE_PARAM(AI, "Association Indication")
